Executable = geng
Universe = vanilla
Arguments =  "10 10 $(Step)/10 -T125"
Output =  "out/10_10_$(Step).out"
Log =  "log/10_10_$(Step).log"
Error =  "err/10_10_$(Step).err"
Queue 10

Arguments =  "10 11 $(Step)/10 -T102"
Output =  "out/10_11_$(Step).out"
Log =  "log/10_11_$(Step).log"
Error =  "err/10_11_$(Step).err"
Queue 10

Arguments =  "10 12 $(Step)/10 -T91"
Output =  "out/10_12_$(Step).out"
Log =  "log/10_12_$(Step).log"
Error =  "err/10_12_$(Step).err"
Queue 10

Arguments =  "10 13 $(Step)/10 -T83"
Output =  "out/10_13_$(Step).out"
Log =  "log/10_13_$(Step).log"
Error =  "err/10_13_$(Step).err"
Queue 10

Arguments =  "10 14 $(Step)/10 -T78"
Output =  "out/10_14_$(Step).out"
Log =  "log/10_14_$(Step).log"
Error =  "err/10_14_$(Step).err"
Queue 10

Arguments =  "11 11 $(Step)/10 -T165"
Output =  "out/11_11_$(Step).out"
Log =  "log/11_11_$(Step).log"
Error =  "err/11_11_$(Step).err"
Queue 10

Arguments =  "11 12 $(Step)/10 -T136"
Output =  "out/11_12_$(Step).out"
Log =  "log/11_12_$(Step).log"
Error =  "err/11_12_$(Step).err"
Queue 10

Arguments =  "11 13 $(Step)/10 -T118"
Output =  "out/11_13_$(Step).out"
Log =  "log/11_13_$(Step).log"
Error =  "err/11_13_$(Step).err"
Queue 10

Arguments =  "11 14 $(Step)/10 -T108"
Output =  "out/11_14_$(Step).out"
Log =  "log/11_14_$(Step).log"
Error =  "err/11_14_$(Step).err"
Queue 10

Arguments =  "11 15 $(Step)/10 -T101"
Output =  "out/11_15_$(Step).out"
Log =  "log/11_15_$(Step).log"
Error =  "err/11_15_$(Step).err"
Queue 10

Arguments =  "11 16 $(Step)/10 -T96"
Output =  "out/11_16_$(Step).out"
Log =  "log/11_16_$(Step).log"
Error =  "err/11_16_$(Step).err"
Queue 10

Arguments =  "12 12 $(Step)/10 -T216"
Output =  "out/12_12_$(Step).out"
Log =  "log/12_12_$(Step).log"
Error =  "err/12_12_$(Step).err"
Queue 10

Arguments =  "12 13 $(Step)/10 -T174"
Output =  "out/12_13_$(Step).out"
Log =  "log/12_13_$(Step).log"
Error =  "err/12_13_$(Step).err"
Queue 10

Arguments =  "12 14 $(Step)/10 -T151"
Output =  "out/12_14_$(Step).out"
Log =  "log/12_14_$(Step).log"
Error =  "err/12_14_$(Step).err"
Queue 10

Arguments =  "12 15 $(Step)/10 -T138"
Output =  "out/12_15_$(Step).out"
Log =  "log/12_15_$(Step).log"
Error =  "err/12_15_$(Step).err"
Queue 10

Arguments =  "12 16 $(Step)/10 -T128"
Output =  "out/12_16_$(Step).out"
Log =  "log/12_16_$(Step).log"
Error =  "err/12_16_$(Step).err"
Queue 10

Arguments =  "12 17 $(Step)/10 -T121"
Output =  "out/12_17_$(Step).out"
Log =  "log/12_17_$(Step).log"
Error =  "err/12_17_$(Step).err"
Queue 10

Arguments =  "12 18 $(Step)/10 -T116"
Output =  "out/12_18_$(Step).out"
Log =  "log/12_18_$(Step).log"
Error =  "err/12_18_$(Step).err"
Queue 10

Arguments =  "13 13 $(Step)/10 -T273"
Output =  "out/13_13_$(Step).out"
Log =  "log/13_13_$(Step).log"
Error =  "err/13_13_$(Step).err"
Queue 10

Arguments =  "13 14 $(Step)/10 -T220"
Output =  "out/13_14_$(Step).out"
Log =  "log/13_14_$(Step).log"
Error =  "err/13_14_$(Step).err"
Queue 10

Arguments =  "13 15 $(Step)/10 -T190"
Output =  "out/13_15_$(Step).out"
Log =  "log/13_15_$(Step).log"
Error =  "err/13_15_$(Step).err"
Queue 10

Arguments =  "13 16 $(Step)/10 -T171"
Output =  "out/13_16_$(Step).out"
Log =  "log/13_16_$(Step).log"
Error =  "err/13_16_$(Step).err"
Queue 10

Arguments =  "13 17 $(Step)/10 -T159"
Output =  "out/13_17_$(Step).out"
Log =  "log/13_17_$(Step).log"
Error =  "err/13_17_$(Step).err"
Queue 10

Arguments =  "13 18 $(Step)/10 -T150"
Output =  "out/13_18_$(Step).out"
Log =  "log/13_18_$(Step).log"
Error =  "err/13_18_$(Step).err"
Queue 10

Arguments =  "13 19 $(Step)/10 -T143"
Output =  "out/13_19_$(Step).out"
Log =  "log/13_19_$(Step).log"
Error =  "err/13_19_$(Step).err"
Queue 10

Arguments =  "13 20 $(Step)/10 -T138"
Output =  "out/13_20_$(Step).out"
Log =  "log/13_20_$(Step).log"
Error =  "err/13_20_$(Step).err"
Queue 10

Arguments =  "14 14 $(Step)/10 -T343"
Output =  "out/14_14_$(Step).out"
Log =  "log/14_14_$(Step).log"
Error =  "err/14_14_$(Step).err"
Queue 10

Arguments =  "14 15 $(Step)/10 -T275"
Output =  "out/14_15_$(Step).out"
Log =  "log/14_15_$(Step).log"
Error =  "err/14_15_$(Step).err"
Queue 10

Arguments =  "14 16 $(Step)/10 -T236"
Output =  "out/14_16_$(Step).out"
Log =  "log/14_16_$(Step).log"
Error =  "err/14_16_$(Step).err"
Queue 10

Arguments =  "14 17 $(Step)/10 -T210"
Output =  "out/14_17_$(Step).out"
Log =  "log/14_17_$(Step).log"
Error =  "err/14_17_$(Step).err"
Queue 10

Arguments =  "14 18 $(Step)/10 -T195"
Output =  "out/14_18_$(Step).out"
Log =  "log/14_18_$(Step).log"
Error =  "err/14_18_$(Step).err"
Queue 10

Arguments =  "14 19 $(Step)/10 -T183"
Output =  "out/14_19_$(Step).out"
Log =  "log/14_19_$(Step).log"
Error =  "err/14_19_$(Step).err"
Queue 10

Arguments =  "14 20 $(Step)/10 -T174"
Output =  "out/14_20_$(Step).out"
Log =  "log/14_20_$(Step).log"
Error =  "err/14_20_$(Step).err"
Queue 10

Arguments =  "14 21 $(Step)/10 -T167"
Output =  "out/14_21_$(Step).out"
Log =  "log/14_21_$(Step).log"
Error =  "err/14_21_$(Step).err"
Queue 10

Arguments =  "14 22 $(Step)/10 -T162"
Output =  "out/14_22_$(Step).out"
Log =  "log/14_22_$(Step).log"
Error =  "err/14_22_$(Step).err"
Queue 10

Arguments =  "15 15 $(Step)/10 -T420"
Output =  "out/15_15_$(Step).out"
Log =  "log/15_15_$(Step).log"
Error =  "err/15_15_$(Step).err"
Queue 10

Arguments =  "15 16 $(Step)/10 -T335"
Output =  "out/15_16_$(Step).out"
Log =  "log/15_16_$(Step).log"
Error =  "err/15_16_$(Step).err"
Queue 10

Arguments =  "15 17 $(Step)/10 -T286"
Output =  "out/15_17_$(Step).out"
Log =  "log/15_17_$(Step).log"
Error =  "err/15_17_$(Step).err"
Queue 10

Arguments =  "15 18 $(Step)/10 -T255"
Output =  "out/15_18_$(Step).out"
Log =  "log/15_18_$(Step).log"
Error =  "err/15_18_$(Step).err"
Queue 10

Arguments =  "15 19 $(Step)/10 -T234"
Output =  "out/15_19_$(Step).out"
Log =  "log/15_19_$(Step).log"
Error =  "err/15_19_$(Step).err"
Queue 10

Arguments =  "15 20 $(Step)/10 -T220"
Output =  "out/15_20_$(Step).out"
Log =  "log/15_20_$(Step).log"
Error =  "err/15_20_$(Step).err"
Queue 10

Arguments =  "15 21 $(Step)/10 -T209"
Output =  "out/15_21_$(Step).out"
Log =  "log/15_21_$(Step).log"
Error =  "err/15_21_$(Step).err"
Queue 10

Arguments =  "15 22 $(Step)/10 -T200"
Output =  "out/15_22_$(Step).out"
Log =  "log/15_22_$(Step).log"
Error =  "err/15_22_$(Step).err"
Queue 10

Arguments =  "15 23 $(Step)/10 -T193"
Output =  "out/15_23_$(Step).out"
Log =  "log/15_23_$(Step).log"
Error =  "err/15_23_$(Step).err"
Queue 10

Arguments =  "15 24 $(Step)/10 -T188"
Output =  "out/15_24_$(Step).out"
Log =  "log/15_24_$(Step).log"
Error =  "err/15_24_$(Step).err"
Queue 10

Arguments =  "16 16 $(Step)/10 -T512"
Output =  "out/16_16_$(Step).out"
Log =  "log/16_16_$(Step).log"
Error =  "err/16_16_$(Step).err"
Queue 10

Arguments =  "16 17 $(Step)/10 -T405"
Output =  "out/16_17_$(Step).out"
Log =  "log/16_17_$(Step).log"
Error =  "err/16_17_$(Step).err"
Queue 10

Arguments =  "16 18 $(Step)/10 -T344"
Output =  "out/16_18_$(Step).out"
Log =  "log/16_18_$(Step).log"
Error =  "err/16_18_$(Step).err"
Queue 10

Arguments =  "16 19 $(Step)/10 -T306"
Output =  "out/16_19_$(Step).out"
Log =  "log/16_19_$(Step).log"
Error =  "err/16_19_$(Step).err"
Queue 10

Arguments =  "16 20 $(Step)/10 -T279"
Output =  "out/16_20_$(Step).out"
Log =  "log/16_20_$(Step).log"
Error =  "err/16_20_$(Step).err"
Queue 10

Arguments =  "16 21 $(Step)/10 -T262"
Output =  "out/16_21_$(Step).out"
Log =  "log/16_21_$(Step).log"
Error =  "err/16_21_$(Step).err"
Queue 10

Arguments =  "16 22 $(Step)/10 -T248"
Output =  "out/16_22_$(Step).out"
Log =  "log/16_22_$(Step).log"
Error =  "err/16_22_$(Step).err"
Queue 10

Arguments =  "16 23 $(Step)/10 -T237"
Output =  "out/16_23_$(Step).out"
Log =  "log/16_23_$(Step).log"
Error =  "err/16_23_$(Step).err"
Queue 10

Arguments =  "16 24 $(Step)/10 -T228"
Output =  "out/16_24_$(Step).out"
Log =  "log/16_24_$(Step).log"
Error =  "err/16_24_$(Step).err"
Queue 10

Arguments =  "16 25 $(Step)/10 -T221"
Output =  "out/16_25_$(Step).out"
Log =  "log/16_25_$(Step).log"
Error =  "err/16_25_$(Step).err"
Queue 10

Arguments =  "16 26 $(Step)/10 -T216"
Output =  "out/16_26_$(Step).out"
Log =  "log/16_26_$(Step).log"
Error =  "err/16_26_$(Step).err"
Queue 10

Arguments =  "17 17 $(Step)/10 -T612"
Output =  "out/17_17_$(Step).out"
Log =  "log/17_17_$(Step).log"
Error =  "err/17_17_$(Step).err"
Queue 10

Arguments =  "17 18 $(Step)/10 -T486"
Output =  "out/17_18_$(Step).out"
Log =  "log/17_18_$(Step).log"
Error =  "err/17_18_$(Step).err"
Queue 10

Arguments =  "17 19 $(Step)/10 -T410"
Output =  "out/17_19_$(Step).out"
Log =  "log/17_19_$(Step).log"
Error =  "err/17_19_$(Step).err"
Queue 10

Arguments =  "17 20 $(Step)/10 -T364"
Output =  "out/17_20_$(Step).out"
Log =  "log/17_20_$(Step).log"
Error =  "err/17_20_$(Step).err"
Queue 10

Arguments =  "17 21 $(Step)/10 -T330"
Output =  "out/17_21_$(Step).out"
Log =  "log/17_21_$(Step).log"
Error =  "err/17_21_$(Step).err"
Queue 10

Arguments =  "17 22 $(Step)/10 -T307"
Output =  "out/17_22_$(Step).out"
Log =  "log/17_22_$(Step).log"
Error =  "err/17_22_$(Step).err"
Queue 10

Arguments =  "17 23 $(Step)/10 -T291"
Output =  "out/17_23_$(Step).out"
Log =  "log/17_23_$(Step).log"
Error =  "err/17_23_$(Step).err"
Queue 10

Arguments =  "17 24 $(Step)/10 -T278"
Output =  "out/17_24_$(Step).out"
Log =  "log/17_24_$(Step).log"
Error =  "err/17_24_$(Step).err"
Queue 10

Arguments =  "17 25 $(Step)/10 -T267"
Output =  "out/17_25_$(Step).out"
Log =  "log/17_25_$(Step).log"
Error =  "err/17_25_$(Step).err"
Queue 10

Arguments =  "17 26 $(Step)/10 -T258"
Output =  "out/17_26_$(Step).out"
Log =  "log/17_26_$(Step).log"
Error =  "err/17_26_$(Step).err"
Queue 10

Arguments =  "17 27 $(Step)/10 -T251"
Output =  "out/17_27_$(Step).out"
Log =  "log/17_27_$(Step).log"
Error =  "err/17_27_$(Step).err"
Queue 10

Arguments =  "17 28 $(Step)/10 -T246"
Output =  "out/17_28_$(Step).out"
Log =  "log/17_28_$(Step).log"
Error =  "err/17_28_$(Step).err"
Queue 10

Arguments =  "18 18 $(Step)/10 -T729"
Output =  "out/18_18_$(Step).out"
Log =  "log/18_18_$(Step).log"
Error =  "err/18_18_$(Step).err"
Queue 10

Arguments =  "18 19 $(Step)/10 -T573"
Output =  "out/18_19_$(Step).out"
Log =  "log/18_19_$(Step).log"
Error =  "err/18_19_$(Step).err"
Queue 10

Arguments =  "18 20 $(Step)/10 -T485"
Output =  "out/18_20_$(Step).out"
Log =  "log/18_20_$(Step).log"
Error =  "err/18_20_$(Step).err"
Queue 10

Arguments =  "18 21 $(Step)/10 -T426"
Output =  "out/18_21_$(Step).out"
Log =  "log/18_21_$(Step).log"
Error =  "err/18_21_$(Step).err"
Queue 10

Arguments =  "18 22 $(Step)/10 -T387"
Output =  "out/18_22_$(Step).out"
Log =  "log/18_22_$(Step).log"
Error =  "err/18_22_$(Step).err"
Queue 10

Arguments =  "18 23 $(Step)/10 -T358"
Output =  "out/18_23_$(Step).out"
Log =  "log/18_23_$(Step).log"
Error =  "err/18_23_$(Step).err"
Queue 10

Arguments =  "18 24 $(Step)/10 -T339"
Output =  "out/18_24_$(Step).out"
Log =  "log/18_24_$(Step).log"
Error =  "err/18_24_$(Step).err"
Queue 10

Arguments =  "18 25 $(Step)/10 -T323"
Output =  "out/18_25_$(Step).out"
Log =  "log/18_25_$(Step).log"
Error =  "err/18_25_$(Step).err"
Queue 10

Arguments =  "18 26 $(Step)/10 -T310"
Output =  "out/18_26_$(Step).out"
Log =  "log/18_26_$(Step).log"
Error =  "err/18_26_$(Step).err"
Queue 10

Arguments =  "18 27 $(Step)/10 -T299"
Output =  "out/18_27_$(Step).out"
Log =  "log/18_27_$(Step).log"
Error =  "err/18_27_$(Step).err"
Queue 10

Arguments =  "18 28 $(Step)/10 -T290"
Output =  "out/18_28_$(Step).out"
Log =  "log/18_28_$(Step).log"
Error =  "err/18_28_$(Step).err"
Queue 10

Arguments =  "18 29 $(Step)/10 -T283"
Output =  "out/18_29_$(Step).out"
Log =  "log/18_29_$(Step).log"
Error =  "err/18_29_$(Step).err"
Queue 10

Arguments =  "18 30 $(Step)/10 -T278"
Output =  "out/18_30_$(Step).out"
Log =  "log/18_30_$(Step).log"
Error =  "err/18_30_$(Step).err"
Queue 10

Arguments =  "19 19 $(Step)/10 -T855"
Output =  "out/19_19_$(Step).out"
Log =  "log/19_19_$(Step).log"
Error =  "err/19_19_$(Step).err"
Queue 10

Arguments =  "19 20 $(Step)/10 -T672"
Output =  "out/19_20_$(Step).out"
Log =  "log/19_20_$(Step).log"
Error =  "err/19_20_$(Step).err"
Queue 10

Arguments =  "19 21 $(Step)/10 -T565"
Output =  "out/19_21_$(Step).out"
Log =  "log/19_21_$(Step).log"
Error =  "err/19_21_$(Step).err"
Queue 10

Arguments =  "19 22 $(Step)/10 -T496"
Output =  "out/19_22_$(Step).out"
Log =  "log/19_22_$(Step).log"
Error =  "err/19_22_$(Step).err"
Queue 10

Arguments =  "19 23 $(Step)/10 -T450"
Output =  "out/19_23_$(Step).out"
Log =  "log/19_23_$(Step).log"
Error =  "err/19_23_$(Step).err"
Queue 10

Arguments =  "19 24 $(Step)/10 -T415"
Output =  "out/19_24_$(Step).out"
Log =  "log/19_24_$(Step).log"
Error =  "err/19_24_$(Step).err"
Queue 10

Arguments =  "19 25 $(Step)/10 -T390"
Output =  "out/19_25_$(Step).out"
Log =  "log/19_25_$(Step).log"
Error =  "err/19_25_$(Step).err"
Queue 10

Arguments =  "19 26 $(Step)/10 -T372"
Output =  "out/19_26_$(Step).out"
Log =  "log/19_26_$(Step).log"
Error =  "err/19_26_$(Step).err"
Queue 10

Arguments =  "19 27 $(Step)/10 -T357"
Output =  "out/19_27_$(Step).out"
Log =  "log/19_27_$(Step).log"
Error =  "err/19_27_$(Step).err"
Queue 10

Arguments =  "19 28 $(Step)/10 -T344"
Output =  "out/19_28_$(Step).out"
Log =  "log/19_28_$(Step).log"
Error =  "err/19_28_$(Step).err"
Queue 10

Arguments =  "19 29 $(Step)/10 -T333"
Output =  "out/19_29_$(Step).out"
Log =  "log/19_29_$(Step).log"
Error =  "err/19_29_$(Step).err"
Queue 10

Arguments =  "19 30 $(Step)/10 -T324"
Output =  "out/19_30_$(Step).out"
Log =  "log/19_30_$(Step).log"
Error =  "err/19_30_$(Step).err"
Queue 10

Arguments =  "19 31 $(Step)/10 -T317"
Output =  "out/19_31_$(Step).out"
Log =  "log/19_31_$(Step).log"
Error =  "err/19_31_$(Step).err"
Queue 10

Arguments =  "19 32 $(Step)/10 -T312"
Output =  "out/19_32_$(Step).out"
Log =  "log/19_32_$(Step).log"
Error =  "err/19_32_$(Step).err"
Queue 10

Arguments =  "20 20 $(Step)/10 -T1000"
Output =  "out/20_20_$(Step).out"
Log =  "log/20_20_$(Step).log"
Error =  "err/20_20_$(Step).err"
Queue 10

Arguments =  "20 21 $(Step)/10 -T784"
Output =  "out/20_21_$(Step).out"
Log =  "log/20_21_$(Step).log"
Error =  "err/20_21_$(Step).err"
Queue 10

Arguments =  "20 22 $(Step)/10 -T655"
Output =  "out/20_22_$(Step).out"
Log =  "log/20_22_$(Step).log"
Error =  "err/20_22_$(Step).err"
Queue 10

Arguments =  "20 23 $(Step)/10 -T574"
Output =  "out/20_23_$(Step).out"
Log =  "log/20_23_$(Step).log"
Error =  "err/20_23_$(Step).err"
Queue 10

Arguments =  "20 24 $(Step)/10 -T520"
Output =  "out/20_24_$(Step).out"
Log =  "log/20_24_$(Step).log"
Error =  "err/20_24_$(Step).err"
Queue 10

Arguments =  "20 25 $(Step)/10 -T478"
Output =  "out/20_25_$(Step).out"
Log =  "log/20_25_$(Step).log"
Error =  "err/20_25_$(Step).err"
Queue 10

Arguments =  "20 26 $(Step)/10 -T447"
Output =  "out/20_26_$(Step).out"
Log =  "log/20_26_$(Step).log"
Error =  "err/20_26_$(Step).err"
Queue 10

Arguments =  "20 27 $(Step)/10 -T426"
Output =  "out/20_27_$(Step).out"
Log =  "log/20_27_$(Step).log"
Error =  "err/20_27_$(Step).err"
Queue 10

Arguments =  "20 28 $(Step)/10 -T408"
Output =  "out/20_28_$(Step).out"
Log =  "log/20_28_$(Step).log"
Error =  "err/20_28_$(Step).err"
Queue 10

Arguments =  "20 29 $(Step)/10 -T393"
Output =  "out/20_29_$(Step).out"
Log =  "log/20_29_$(Step).log"
Error =  "err/20_29_$(Step).err"
Queue 10

Arguments =  "20 30 $(Step)/10 -T380"
Output =  "out/20_30_$(Step).out"
Log =  "log/20_30_$(Step).log"
Error =  "err/20_30_$(Step).err"
Queue 10

Arguments =  "20 31 $(Step)/10 -T369"
Output =  "out/20_31_$(Step).out"
Log =  "log/20_31_$(Step).log"
Error =  "err/20_31_$(Step).err"
Queue 10

Arguments =  "20 32 $(Step)/10 -T360"
Output =  "out/20_32_$(Step).out"
Log =  "log/20_32_$(Step).log"
Error =  "err/20_32_$(Step).err"
Queue 10

Arguments =  "20 33 $(Step)/10 -T353"
Output =  "out/20_33_$(Step).out"
Log =  "log/20_33_$(Step).log"
Error =  "err/20_33_$(Step).err"
Queue 10

Arguments =  "20 34 $(Step)/10 -T348"
Output =  "out/20_34_$(Step).out"
Log =  "log/20_34_$(Step).log"
Error =  "err/20_34_$(Step).err"
Queue 10

Arguments =  "21 21 $(Step)/10 -T1155"
Output =  "out/21_21_$(Step).out"
Log =  "log/21_21_$(Step).log"
Error =  "err/21_21_$(Step).err"
Queue 10

Arguments =  "21 22 $(Step)/10 -T903"
Output =  "out/21_22_$(Step).out"
Log =  "log/21_22_$(Step).log"
Error =  "err/21_22_$(Step).err"
Queue 10

Arguments =  "21 23 $(Step)/10 -T755"
Output =  "out/21_23_$(Step).out"
Log =  "log/21_23_$(Step).log"
Error =  "err/21_23_$(Step).err"
Queue 10

Arguments =  "21 24 $(Step)/10 -T660"
Output =  "out/21_24_$(Step).out"
Log =  "log/21_24_$(Step).log"
Error =  "err/21_24_$(Step).err"
Queue 10

Arguments =  "21 25 $(Step)/10 -T594"
Output =  "out/21_25_$(Step).out"
Log =  "log/21_25_$(Step).log"
Error =  "err/21_25_$(Step).err"
Queue 10

Arguments =  "21 26 $(Step)/10 -T547"
Output =  "out/21_26_$(Step).out"
Log =  "log/21_26_$(Step).log"
Error =  "err/21_26_$(Step).err"
Queue 10

Arguments =  "21 27 $(Step)/10 -T510"
Output =  "out/21_27_$(Step).out"
Log =  "log/21_27_$(Step).log"
Error =  "err/21_27_$(Step).err"
Queue 10

Arguments =  "21 28 $(Step)/10 -T483"
Output =  "out/21_28_$(Step).out"
Log =  "log/21_28_$(Step).log"
Error =  "err/21_28_$(Step).err"
Queue 10

Arguments =  "21 29 $(Step)/10 -T463"
Output =  "out/21_29_$(Step).out"
Log =  "log/21_29_$(Step).log"
Error =  "err/21_29_$(Step).err"
Queue 10

Arguments =  "21 30 $(Step)/10 -T446"
Output =  "out/21_30_$(Step).out"
Log =  "log/21_30_$(Step).log"
Error =  "err/21_30_$(Step).err"
Queue 10

Arguments =  "21 31 $(Step)/10 -T431"
Output =  "out/21_31_$(Step).out"
Log =  "log/21_31_$(Step).log"
Error =  "err/21_31_$(Step).err"
Queue 10

Arguments =  "21 32 $(Step)/10 -T418"
Output =  "out/21_32_$(Step).out"
Log =  "log/21_32_$(Step).log"
Error =  "err/21_32_$(Step).err"
Queue 10

Arguments =  "21 33 $(Step)/10 -T407"
Output =  "out/21_33_$(Step).out"
Log =  "log/21_33_$(Step).log"
Error =  "err/21_33_$(Step).err"
Queue 10

Arguments =  "21 34 $(Step)/10 -T398"
Output =  "out/21_34_$(Step).out"
Log =  "log/21_34_$(Step).log"
Error =  "err/21_34_$(Step).err"
Queue 10

Arguments =  "21 35 $(Step)/10 -T391"
Output =  "out/21_35_$(Step).out"
Log =  "log/21_35_$(Step).log"
Error =  "err/21_35_$(Step).err"
Queue 10

Arguments =  "21 36 $(Step)/10 -T386"
Output =  "out/21_36_$(Step).out"
Log =  "log/21_36_$(Step).log"
Error =  "err/21_36_$(Step).err"
Queue 10

Arguments =  "22 22 $(Step)/10 -T1331"
Output =  "out/22_22_$(Step).out"
Log =  "log/22_22_$(Step).log"
Error =  "err/22_22_$(Step).err"
Queue 10

Arguments =  "22 23 $(Step)/10 -T1036"
Output =  "out/22_23_$(Step).out"
Log =  "log/22_23_$(Step).log"
Error =  "err/22_23_$(Step).err"
Queue 10

Arguments =  "22 24 $(Step)/10 -T866"
Output =  "out/22_24_$(Step).out"
Log =  "log/22_24_$(Step).log"
Error =  "err/22_24_$(Step).err"
Queue 10

Arguments =  "22 25 $(Step)/10 -T755"
Output =  "out/22_25_$(Step).out"
Log =  "log/22_25_$(Step).log"
Error =  "err/22_25_$(Step).err"
Queue 10

Arguments =  "22 26 $(Step)/10 -T676"
Output =  "out/22_26_$(Step).out"
Log =  "log/22_26_$(Step).log"
Error =  "err/22_26_$(Step).err"
Queue 10

Arguments =  "22 27 $(Step)/10 -T622"
Output =  "out/22_27_$(Step).out"
Log =  "log/22_27_$(Step).log"
Error =  "err/22_27_$(Step).err"
Queue 10

Arguments =  "22 28 $(Step)/10 -T579"
Output =  "out/22_28_$(Step).out"
Log =  "log/22_28_$(Step).log"
Error =  "err/22_28_$(Step).err"
Queue 10

Arguments =  "22 29 $(Step)/10 -T546"
Output =  "out/22_29_$(Step).out"
Log =  "log/22_29_$(Step).log"
Error =  "err/22_29_$(Step).err"
Queue 10

Arguments =  "22 30 $(Step)/10 -T523"
Output =  "out/22_30_$(Step).out"
Log =  "log/22_30_$(Step).log"
Error =  "err/22_30_$(Step).err"
Queue 10

Arguments =  "22 31 $(Step)/10 -T503"
Output =  "out/22_31_$(Step).out"
Log =  "log/22_31_$(Step).log"
Error =  "err/22_31_$(Step).err"
Queue 10

Arguments =  "22 32 $(Step)/10 -T486"
Output =  "out/22_32_$(Step).out"
Log =  "log/22_32_$(Step).log"
Error =  "err/22_32_$(Step).err"
Queue 10

Arguments =  "22 33 $(Step)/10 -T471"
Output =  "out/22_33_$(Step).out"
Log =  "log/22_33_$(Step).log"
Error =  "err/22_33_$(Step).err"
Queue 10

Arguments =  "22 34 $(Step)/10 -T458"
Output =  "out/22_34_$(Step).out"
Log =  "log/22_34_$(Step).log"
Error =  "err/22_34_$(Step).err"
Queue 10

Arguments =  "22 35 $(Step)/10 -T447"
Output =  "out/22_35_$(Step).out"
Log =  "log/22_35_$(Step).log"
Error =  "err/22_35_$(Step).err"
Queue 10

Arguments =  "22 36 $(Step)/10 -T438"
Output =  "out/22_36_$(Step).out"
Log =  "log/22_36_$(Step).log"
Error =  "err/22_36_$(Step).err"
Queue 10

Arguments =  "22 37 $(Step)/10 -T431"
Output =  "out/22_37_$(Step).out"
Log =  "log/22_37_$(Step).log"
Error =  "err/22_37_$(Step).err"
Queue 10

Arguments =  "22 38 $(Step)/10 -T426"
Output =  "out/22_38_$(Step).out"
Log =  "log/22_38_$(Step).log"
Error =  "err/22_38_$(Step).err"
Queue 10

Arguments =  "23 23 $(Step)/10 -T1518"
Output =  "out/23_23_$(Step).out"
Log =  "log/23_23_$(Step).log"
Error =  "err/23_23_$(Step).err"
Queue 10

Arguments =  "23 24 $(Step)/10 -T1184"
Output =  "out/23_24_$(Step).out"
Log =  "log/23_24_$(Step).log"
Error =  "err/23_24_$(Step).err"
Queue 10

Arguments =  "23 25 $(Step)/10 -T983"
Output =  "out/23_25_$(Step).out"
Log =  "log/23_25_$(Step).log"
Error =  "err/23_25_$(Step).err"
Queue 10

Arguments =  "23 26 $(Step)/10 -T855"
Output =  "out/23_26_$(Step).out"
Log =  "log/23_26_$(Step).log"
Error =  "err/23_26_$(Step).err"
Queue 10

Arguments =  "23 27 $(Step)/10 -T766"
Output =  "out/23_27_$(Step).out"
Log =  "log/23_27_$(Step).log"
Error =  "err/23_27_$(Step).err"
Queue 10

Arguments =  "23 28 $(Step)/10 -T704"
Output =  "out/23_28_$(Step).out"
Log =  "log/23_28_$(Step).log"
Error =  "err/23_28_$(Step).err"
Queue 10

Arguments =  "23 29 $(Step)/10 -T654"
Output =  "out/23_29_$(Step).out"
Log =  "log/23_29_$(Step).log"
Error =  "err/23_29_$(Step).err"
Queue 10

Arguments =  "23 30 $(Step)/10 -T615"
Output =  "out/23_30_$(Step).out"
Log =  "log/23_30_$(Step).log"
Error =  "err/23_30_$(Step).err"
Queue 10

Arguments =  "23 31 $(Step)/10 -T586"
Output =  "out/23_31_$(Step).out"
Log =  "log/23_31_$(Step).log"
Error =  "err/23_31_$(Step).err"
Queue 10

Arguments =  "23 32 $(Step)/10 -T564"
Output =  "out/23_32_$(Step).out"
Log =  "log/23_32_$(Step).log"
Error =  "err/23_32_$(Step).err"
Queue 10

Arguments =  "23 33 $(Step)/10 -T545"
Output =  "out/23_33_$(Step).out"
Log =  "log/23_33_$(Step).log"
Error =  "err/23_33_$(Step).err"
Queue 10

Arguments =  "23 34 $(Step)/10 -T528"
Output =  "out/23_34_$(Step).out"
Log =  "log/23_34_$(Step).log"
Error =  "err/23_34_$(Step).err"
Queue 10

Arguments =  "23 35 $(Step)/10 -T513"
Output =  "out/23_35_$(Step).out"
Log =  "log/23_35_$(Step).log"
Error =  "err/23_35_$(Step).err"
Queue 10

Arguments =  "23 36 $(Step)/10 -T500"
Output =  "out/23_36_$(Step).out"
Log =  "log/23_36_$(Step).log"
Error =  "err/23_36_$(Step).err"
Queue 10

Arguments =  "23 37 $(Step)/10 -T489"
Output =  "out/23_37_$(Step).out"
Log =  "log/23_37_$(Step).log"
Error =  "err/23_37_$(Step).err"
Queue 10

Arguments =  "23 38 $(Step)/10 -T480"
Output =  "out/23_38_$(Step).out"
Log =  "log/23_38_$(Step).log"
Error =  "err/23_38_$(Step).err"
Queue 10

Arguments =  "23 39 $(Step)/10 -T473"
Output =  "out/23_39_$(Step).out"
Log =  "log/23_39_$(Step).log"
Error =  "err/23_39_$(Step).err"
Queue 10

Arguments =  "23 40 $(Step)/10 -T468"
Output =  "out/23_40_$(Step).out"
Log =  "log/23_40_$(Step).log"
Error =  "err/23_40_$(Step).err"
Queue 10

Arguments =  "24 24 $(Step)/10 -T1728"
Output =  "out/24_24_$(Step).out"
Log =  "log/24_24_$(Step).log"
Error =  "err/24_24_$(Step).err"
Queue 10

Arguments =  "24 25 $(Step)/10 -T1340"
Output =  "out/24_25_$(Step).out"
Log =  "log/24_25_$(Step).log"
Error =  "err/24_25_$(Step).err"
Queue 10

Arguments =  "24 26 $(Step)/10 -T1112"
Output =  "out/24_26_$(Step).out"
Log =  "log/24_26_$(Step).log"
Error =  "err/24_26_$(Step).err"
Queue 10

Arguments =  "24 27 $(Step)/10 -T965"
Output =  "out/24_27_$(Step).out"
Log =  "log/24_27_$(Step).log"
Error =  "err/24_27_$(Step).err"
Queue 10

Arguments =  "24 28 $(Step)/10 -T864"
Output =  "out/24_28_$(Step).out"
Log =  "log/24_28_$(Step).log"
Error =  "err/24_28_$(Step).err"
Queue 10

Arguments =  "24 29 $(Step)/10 -T790"
Output =  "out/24_29_$(Step).out"
Log =  "log/24_29_$(Step).log"
Error =  "err/24_29_$(Step).err"
Queue 10

Arguments =  "24 30 $(Step)/10 -T735"
Output =  "out/24_30_$(Step).out"
Log =  "log/24_30_$(Step).log"
Error =  "err/24_30_$(Step).err"
Queue 10

Arguments =  "24 31 $(Step)/10 -T690"
Output =  "out/24_31_$(Step).out"
Log =  "log/24_31_$(Step).log"
Error =  "err/24_31_$(Step).err"
Queue 10

Arguments =  "24 32 $(Step)/10 -T655"
Output =  "out/24_32_$(Step).out"
Log =  "log/24_32_$(Step).log"
Error =  "err/24_32_$(Step).err"
Queue 10

Arguments =  "24 33 $(Step)/10 -T630"
Output =  "out/24_33_$(Step).out"
Log =  "log/24_33_$(Step).log"
Error =  "err/24_33_$(Step).err"
Queue 10

Arguments =  "24 34 $(Step)/10 -T608"
Output =  "out/24_34_$(Step).out"
Log =  "log/24_34_$(Step).log"
Error =  "err/24_34_$(Step).err"
Queue 10

Arguments =  "24 35 $(Step)/10 -T589"
Output =  "out/24_35_$(Step).out"
Log =  "log/24_35_$(Step).log"
Error =  "err/24_35_$(Step).err"
Queue 10

Arguments =  "24 36 $(Step)/10 -T572"
Output =  "out/24_36_$(Step).out"
Log =  "log/24_36_$(Step).log"
Error =  "err/24_36_$(Step).err"
Queue 10

Arguments =  "24 37 $(Step)/10 -T557"
Output =  "out/24_37_$(Step).out"
Log =  "log/24_37_$(Step).log"
Error =  "err/24_37_$(Step).err"
Queue 10

Arguments =  "24 38 $(Step)/10 -T544"
Output =  "out/24_38_$(Step).out"
Log =  "log/24_38_$(Step).log"
Error =  "err/24_38_$(Step).err"
Queue 10

Arguments =  "24 39 $(Step)/10 -T533"
Output =  "out/24_39_$(Step).out"
Log =  "log/24_39_$(Step).log"
Error =  "err/24_39_$(Step).err"
Queue 10

Arguments =  "24 40 $(Step)/10 -T524"
Output =  "out/24_40_$(Step).out"
Log =  "log/24_40_$(Step).log"
Error =  "err/24_40_$(Step).err"
Queue 10

Arguments =  "24 41 $(Step)/10 -T517"
Output =  "out/24_41_$(Step).out"
Log =  "log/24_41_$(Step).log"
Error =  "err/24_41_$(Step).err"
Queue 10

Arguments =  "24 42 $(Step)/10 -T512"
Output =  "out/24_42_$(Step).out"
Log =  "log/24_42_$(Step).log"
Error =  "err/24_42_$(Step).err"
Queue 10

Arguments =  "25 25 $(Step)/10 -T1950"
Output =  "out/25_25_$(Step).out"
Log =  "log/25_25_$(Step).log"
Error =  "err/25_25_$(Step).err"
Queue 10

Arguments =  "25 26 $(Step)/10 -T1512"
Output =  "out/25_26_$(Step).out"
Log =  "log/25_26_$(Step).log"
Error =  "err/25_26_$(Step).err"
Queue 10

Arguments =  "25 27 $(Step)/10 -T1253"
Output =  "out/25_27_$(Step).out"
Log =  "log/25_27_$(Step).log"
Error =  "err/25_27_$(Step).err"
Queue 10

Arguments =  "25 28 $(Step)/10 -T1085"
Output =  "out/25_28_$(Step).out"
Log =  "log/25_28_$(Step).log"
Error =  "err/25_28_$(Step).err"
Queue 10

Arguments =  "25 29 $(Step)/10 -T970"
Output =  "out/25_29_$(Step).out"
Log =  "log/25_29_$(Step).log"
Error =  "err/25_29_$(Step).err"
Queue 10

Arguments =  "25 30 $(Step)/10 -T884"
Output =  "out/25_30_$(Step).out"
Log =  "log/25_30_$(Step).log"
Error =  "err/25_30_$(Step).err"
Queue 10

Arguments =  "25 31 $(Step)/10 -T822"
Output =  "out/25_31_$(Step).out"
Log =  "log/25_31_$(Step).log"
Error =  "err/25_31_$(Step).err"
Queue 10

Arguments =  "25 32 $(Step)/10 -T771"
Output =  "out/25_32_$(Step).out"
Log =  "log/25_32_$(Step).log"
Error =  "err/25_32_$(Step).err"
Queue 10

Arguments =  "25 33 $(Step)/10 -T730"
Output =  "out/25_33_$(Step).out"
Log =  "log/25_33_$(Step).log"
Error =  "err/25_33_$(Step).err"
Queue 10

Arguments =  "25 34 $(Step)/10 -T699"
Output =  "out/25_34_$(Step).out"
Log =  "log/25_34_$(Step).log"
Error =  "err/25_34_$(Step).err"
Queue 10

Arguments =  "25 35 $(Step)/10 -T675"
Output =  "out/25_35_$(Step).out"
Log =  "log/25_35_$(Step).log"
Error =  "err/25_35_$(Step).err"
Queue 10

Arguments =  "25 36 $(Step)/10 -T654"
Output =  "out/25_36_$(Step).out"
Log =  "log/25_36_$(Step).log"
Error =  "err/25_36_$(Step).err"
Queue 10

Arguments =  "25 37 $(Step)/10 -T635"
Output =  "out/25_37_$(Step).out"
Log =  "log/25_37_$(Step).log"
Error =  "err/25_37_$(Step).err"
Queue 10

Arguments =  "25 38 $(Step)/10 -T618"
Output =  "out/25_38_$(Step).out"
Log =  "log/25_38_$(Step).log"
Error =  "err/25_38_$(Step).err"
Queue 10

Arguments =  "25 39 $(Step)/10 -T603"
Output =  "out/25_39_$(Step).out"
Log =  "log/25_39_$(Step).log"
Error =  "err/25_39_$(Step).err"
Queue 10

Arguments =  "25 40 $(Step)/10 -T590"
Output =  "out/25_40_$(Step).out"
Log =  "log/25_40_$(Step).log"
Error =  "err/25_40_$(Step).err"
Queue 10

Arguments =  "25 41 $(Step)/10 -T579"
Output =  "out/25_41_$(Step).out"
Log =  "log/25_41_$(Step).log"
Error =  "err/25_41_$(Step).err"
Queue 10

Arguments =  "25 42 $(Step)/10 -T570"
Output =  "out/25_42_$(Step).out"
Log =  "log/25_42_$(Step).log"
Error =  "err/25_42_$(Step).err"
Queue 10

Arguments =  "25 43 $(Step)/10 -T563"
Output =  "out/25_43_$(Step).out"
Log =  "log/25_43_$(Step).log"
Error =  "err/25_43_$(Step).err"
Queue 10

Arguments =  "25 44 $(Step)/10 -T558"
Output =  "out/25_44_$(Step).out"
Log =  "log/25_44_$(Step).log"
Error =  "err/25_44_$(Step).err"
Queue 10

Arguments =  "26 26 $(Step)/10 -T2197"
Output =  "out/26_26_$(Step).out"
Log =  "log/26_26_$(Step).log"
Error =  "err/26_26_$(Step).err"
Queue 10

Arguments =  "26 27 $(Step)/10 -T1701"
Output =  "out/26_27_$(Step).out"
Log =  "log/26_27_$(Step).log"
Error =  "err/26_27_$(Step).err"
Queue 10

Arguments =  "26 28 $(Step)/10 -T1407"
Output =  "out/26_28_$(Step).out"
Log =  "log/26_28_$(Step).log"
Error =  "err/26_28_$(Step).err"
Queue 10

Arguments =  "26 29 $(Step)/10 -T1215"
Output =  "out/26_29_$(Step).out"
Log =  "log/26_29_$(Step).log"
Error =  "err/26_29_$(Step).err"
Queue 10

Arguments =  "26 30 $(Step)/10 -T1085"
Output =  "out/26_30_$(Step).out"
Log =  "log/26_30_$(Step).log"
Error =  "err/26_30_$(Step).err"
Queue 10

Arguments =  "26 31 $(Step)/10 -T986"
Output =  "out/26_31_$(Step).out"
Log =  "log/26_31_$(Step).log"
Error =  "err/26_31_$(Step).err"
Queue 10

Arguments =  "26 32 $(Step)/10 -T916"
Output =  "out/26_32_$(Step).out"
Log =  "log/26_32_$(Step).log"
Error =  "err/26_32_$(Step).err"
Queue 10

Arguments =  "26 33 $(Step)/10 -T858"
Output =  "out/26_33_$(Step).out"
Log =  "log/26_33_$(Step).log"
Error =  "err/26_33_$(Step).err"
Queue 10

Arguments =  "26 34 $(Step)/10 -T811"
Output =  "out/26_34_$(Step).out"
Log =  "log/26_34_$(Step).log"
Error =  "err/26_34_$(Step).err"
Queue 10

Arguments =  "26 35 $(Step)/10 -T774"
Output =  "out/26_35_$(Step).out"
Log =  "log/26_35_$(Step).log"
Error =  "err/26_35_$(Step).err"
Queue 10

Arguments =  "26 36 $(Step)/10 -T747"
Output =  "out/26_36_$(Step).out"
Log =  "log/26_36_$(Step).log"
Error =  "err/26_36_$(Step).err"
Queue 10

Arguments =  "26 37 $(Step)/10 -T723"
Output =  "out/26_37_$(Step).out"
Log =  "log/26_37_$(Step).log"
Error =  "err/26_37_$(Step).err"
Queue 10

Arguments =  "26 38 $(Step)/10 -T702"
Output =  "out/26_38_$(Step).out"
Log =  "log/26_38_$(Step).log"
Error =  "err/26_38_$(Step).err"
Queue 10

Arguments =  "26 39 $(Step)/10 -T683"
Output =  "out/26_39_$(Step).out"
Log =  "log/26_39_$(Step).log"
Error =  "err/26_39_$(Step).err"
Queue 10

Arguments =  "26 40 $(Step)/10 -T666"
Output =  "out/26_40_$(Step).out"
Log =  "log/26_40_$(Step).log"
Error =  "err/26_40_$(Step).err"
Queue 10

Arguments =  "26 41 $(Step)/10 -T651"
Output =  "out/26_41_$(Step).out"
Log =  "log/26_41_$(Step).log"
Error =  "err/26_41_$(Step).err"
Queue 10

Arguments =  "26 42 $(Step)/10 -T638"
Output =  "out/26_42_$(Step).out"
Log =  "log/26_42_$(Step).log"
Error =  "err/26_42_$(Step).err"
Queue 10

Arguments =  "26 43 $(Step)/10 -T627"
Output =  "out/26_43_$(Step).out"
Log =  "log/26_43_$(Step).log"
Error =  "err/26_43_$(Step).err"
Queue 10

Arguments =  "26 44 $(Step)/10 -T618"
Output =  "out/26_44_$(Step).out"
Log =  "log/26_44_$(Step).log"
Error =  "err/26_44_$(Step).err"
Queue 10

Arguments =  "26 45 $(Step)/10 -T611"
Output =  "out/26_45_$(Step).out"
Log =  "log/26_45_$(Step).log"
Error =  "err/26_45_$(Step).err"
Queue 10

Arguments =  "26 46 $(Step)/10 -T606"
Output =  "out/26_46_$(Step).out"
Log =  "log/26_46_$(Step).log"
Error =  "err/26_46_$(Step).err"
Queue 10

